name: Main CI

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml

  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    needs: test
